name: Create a release

on:
  # Trigger a stable version release via GitHub's UI, with the ability to specify the type of release.
  workflow_dispatch:
    inputs:
      release_type:
        description: Release type
        required: true
        type: choice
        default: auto
        options:
          - auto
          - custom
          - patch
          - minor
          - major
      custom_version:
        description: The custom version to bump to (only for "custom" type)
        required: false
        type: string
        default: ""

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release_metadata:
    name: Prepare release metadata
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{ steps.release_metadata.outputs.version_number }}
      tag_name: ${{ steps.release_metadata.outputs.tag_name }}
      changelog: ${{ steps.release_metadata.outputs.changelog }}
      release_notes: ${{ steps.release_metadata.outputs.release_notes }}
    steps:
      - uses: apify/workflows/git-cliff-release@main
        name: Prepare release metadata
        id: release_metadata
        with:
          release_type: ${{ inputs.release_type }}
          custom_version: ${{ inputs.custom_version }}
          existing_changelog_path: CHANGELOG.md

  code_checks:
    name: Type and lint check
    uses: ./.github/workflows/run_code_checks.yaml

  create_github_release:
    name: Create github release
    needs: [release_metadata, code_checks]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release_metadata.outputs.tag_name }}
          name: ${{ needs.release_metadata.outputs.version_number }}
          body: ${{ needs.release_metadata.outputs.release_notes }}

  publish_to_pypi:
    name: Publish to PyPI
    needs: [release_metadata, code_checks]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for OIDC authentication.
    environment:
      name: pypi
      url: https://pypi.org/project/apify-haystack
    steps:
      - name: Prepare distribution
        uses: apify/workflows/prepare-pypi-distribution@main
        with:
          package_name: apify-haystack
          is_prerelease: ""
          version_number: ${{ needs.release_metadata.outputs.version_number }}
      # Publishes the package to PyPI using PyPA official GitHub action with OIDC authentication.
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
